### ISSUE TITLE
incompatibility with ESP32

### ISSUE THREAD

**Issue by fralbo** [sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library#1]
Hello,
The library doesn't compile when using on ESP32 board, because of the enum PIN_CTRL in LSM6DS0_REGISTERS enumeration.
would be fine to rename it please.

    enum LSM6DSO_REGISTERS {

      FUNC_CFG_ACCESS        = 0x01,  
      SPFUN_PIN_CTRL               = 0x02,   // Now it's ok to build on ESP32 board

**Comment by MikeFindlay** [comment]
+1 for this issue. Here's the error messages when compiling the Basic Readings Sketch for an ESP32 Dev Module (ESP32 Thing Plus).

[ESP32_Error.txt](https://github.com/sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library/files/6958103/ESP32_Error.txt)

**Comment by edspark** [comment]
Thanks for bringing this to my attention, fixed in the latest commit.
