### ISSUE TITLE
Wrong SPI mode for ESP32

### ISSUE THREAD

**Issue by nikoro1904** [sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library#4]
Hello,
I wasn't able to retrieve (reasonable) data unless I changed the SPI mode for the ESP32 from `SPI_MODE1` to `SPI_MODE0` in the `beginSPICore` method (line 64). The LSM6DSO datasheet (page 34) says the IMU is compatible of SPI modes 0 and 3.
Maybe consider changing this. I'm using a nodemcu-32s board.

**Comment by edspark** [comment]
Fixed [here](https://github.com/sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library/commit/b5d9a8ea3471426dd7bb2ecbaa2a61e9cfbc6917), thanks for the concise issue.
