### ISSUE TITLE
Search for LSM6DSO in Arduino IDE Library Manager doesn't find library

### ISSUE THREAD

**Issue by tactical-snacks** [sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library#5]
Searching for "LSM6DSO" in Arduino IDE Library Manager doesn't find library because library's name ends on "0" or zero instead of "O".

**Comment by edspark** [comment]
Thank you for catching that. When I first wrote the library I thought it was a zero at the end of the IC's name to match the other sensors that ended in a digit. I changed everything but missed the name in the library properties.  Fixed now.
