### ISSUE TITLE
Bug in setGyroDataRate()

### ISSUE THREAD

**Issue by nikoro1904** [sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library#6]
In method `setGyroDataRate(uint16_t rate)` there is a bug:
The first if clause only allows rate values >= 125, but in order to set the gyro ODR to a value of e.g. 104 Hz, values below 125 must be allowed. As '0' is also a case in the switch statement, the if clause should only catch values <0 and >6660.

**Comment by edspark** [comment]
Absolutely right, fixed!
