### ISSUE TITLE
can't set gyro range to 125 dps

### ISSUE THREAD

**Issue by tactical-snacks** [sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library#8]
can't set gyro range to 125 because ... `( range < 250 | range > 2000)`

https://github.com/sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library/blob/a8ebc20eb5cf589082de808b70e19da54c5208e8/src/SparkFunLSM6DSO.cpp#L1169

**Comment by edspark** [comment]
[Fixed](https://github.com/sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library/commit/4addc5ffd7cb71a0481aee259ab85c232aa92afe), thanks for the issue!
